// Generated by CoffeeScript 1.6.2
(function() {
  var ASPECT, FAR, HEIGHT, NEAR, VIEW_ANGLE, WIDTH, camera, container, i, j, mesh, objs, pointLight, radius, render, renderer, rings, scene, segments, sphere, sphereMaterial, _i, _j;

  WIDTH = window.innerWidth;

  HEIGHT = window.innerHeight;

  VIEW_ANGLE = 45;

  ASPECT = WIDTH / HEIGHT;

  NEAR = 0.1;

  FAR = 1000;

  container = document.getElementById('container');

  renderer = new THREE.WebGLRenderer();

  camera = new THREE.PerspectiveCamera(VIEW_ANGLE, ASPECT, NEAR, FAR);

  camera.position.z = 300;

  scene = new THREE.Scene();

  container.appendChild(renderer.domElement);

  sphereMaterial = new THREE.MeshLambertMaterial({
    color: 0xCC00C0
  });

  radius = 50;

  segments = 16;

  rings = 16;

  objs = [];

  for (j = _i = 0; _i <= 3; j = ++_i) {
    for (i = _j = 0; _j <= 5; i = ++_j) {
      mesh = new THREE.SphereGeometry(radius, segments, rings);
      sphere = new THREE.Mesh(mesh, sphereMaterial);
      sphere.position.x = -250 + (i * 100);
      sphere.position.y = -200 + (j * 100);
      objs.push(sphere);
      scene.add(sphere);
    }
  }

  pointLight = new THREE.PointLight(0xFFFFFF);

  pointLight.position.x = 10;

  pointLight.position.y = 50;

  pointLight.position.z = 130;

  scene.add(camera);

  scene.add(pointLight);

  renderer.setSize(WIDTH, HEIGHT);

  render = function() {
    var ob, vert, _k, _l, _len, _len1, _ref;

    requestAnimationFrame(render);
    for (_k = 0, _len = objs.length; _k < _len; _k++) {
      ob = objs[_k];
      ob.rotation.x += 0.01 * Math.random();
      ob.rotation.y += 0.01 * Math.random();
      ob.rotation.z += 0.01 * Math.random();
      ob.geometry.verticesNeedUpdate = true;
      _ref = ob.geometry.vertices;
      for (_l = 0, _len1 = _ref.length; _l < _len1; _l++) {
        vert = _ref[_l];
        vert.x = Math.tan(vert.z) * Math.random() * ob.position.x;
        vert.y = Math.cos(vert.z) * Math.random() * ob.position.y;
      }
    }
    return renderer.render(scene, camera);
  };

  render();

}).call(this);
